Fix(tabs): create tabs panel not update tab bar when async generate it (#1254)
Tencent/tdesign-react pull request #1258
Opened 2022-08-10 06:09 UTC by NWYLZW

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [x] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

https://github.com/Tencent/tdesign-react/issues/1254

### 💡 需求背景和解决方案

#### 具体问题

使用异步 api 去创建 tab panel 的时候会导致 tab nav 的 active index 没办法计算出来

#### 解决方法

* 不使用 itemList 对数据作为 getIndex 函数的 deps，使用实际需要的 value 数组

> 其次需要考虑一种边界情况，所以对默认逻辑进行了优化
> 当用户传入了 value 但是没有传入 tab panel 列表的时候不需要默认选择第一个元素的
> 这个时候 getIndex 函数的返回值应该是 -1
> 
> 目的是为了能够让后面用户传入 tab panel 的时
> <details>
> <summary>tab bar 能够检测到 active id 属性的更新</summary>
> 如果是之前的逻辑，active id 默认为 0，用户后面传入 tab panel 的时候，默认也是第一个元素会导致不更新
> </details>

### 📝 更新日志

- fix(tabs): create tabs panel not update tab bar when async generate it

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-08-12 03:15 UTC, LeeJim requested changes

2022-08-12 03:15 UTC, LeeJim commented on src/tabs/TabNav.tsx
> +      const rollbackVal = activeValue === undefined ? -1 : 0;
rollback的值永远为-1才合理吧？
你这样会导致给的activeValue不正确的时候，tabbar出现在第一个tab上

2022-08-12 03:15 UTC, LeeJim commented on src/tabs/TabNav.tsx
> +  const values = itemList.map((item) => item.value);
values只有在getIndex里面才用到，放外面有点浪费计算？

2022-08-12 05:11 UTC, NWYLZW commented on src/tabs/TabNav.tsx
> +      const rollbackVal = activeValue === undefined ? -1 : 0;
之前 rollback 的值永远是 0
原因是因为，没找到的时候默认选择到第一个上面去

这个是之前的逻辑，我为了保持一致所以判断 activeValue 是否有值来判断是否需要 rollback 到 0
如果需要删掉之前的这个逻辑我觉得可以，但是感觉不太好

2022-08-12 05:16 UTC, NWYLZW commented on src/tabs/TabNav.tsx
> +  const values = itemList.map((item) => item.value);
但是因为原来传入的是一个 `[{}]`，导致的下面 `useCallback` 的 deps 不能判断依赖是否更新
https://github.com/Tencent/tdesign-react/blob/develop/src/tabs/TabNav.tsx#L56-L62

这个地方是为了解决不能判断依赖是否更新才这么写的

2022-08-12 06:32 UTC, LeeJim commented on src/tabs/TabNav.tsx
> +      const rollbackVal = activeValue === undefined ? -1 : 0;
不是就是个错误使用，然后我们将错就错渲染第一个也是极不合理的

2022-08-12 06:44 UTC, LeeJim commented on src/tabs/TabNav.tsx
> +  const values = itemList.map((item) => item.value);
本身的依赖是 itemList，没啥问题，应该是没问题的。

2022-08-12 06:44 UTC, LeeJim commented on src/tabs/TabNav.tsx
> -      return index > -1 ? index : 0;
我的理解是，只要将这个 0 改成 -1 就 OK 了。不需要改动这么多？

2022-08-12 07:54 UTC, NWYLZW commented on src/tabs/TabNav.tsx
> +      const rollbackVal = activeValue === undefined ? -1 : 0;
> 本身就是用户使用错误了，然后我们将错就错渲染第一个也是极不合理的。

我觉得也是这样的，其实我也是想简化这里的代码的

2022-08-12 07:56 UTC, NWYLZW commented on src/tabs/TabNav.tsx
> +  const values = itemList.map((item) => item.value);
> 本身的依赖是 itemList，没啥问题，应该是没问题的。

这个地方我改一下跑个单测确认一下，我觉得不能解决问题

2022-08-12 08:07 UTC, NWYLZW commented on src/tabs/TabNav.tsx
> +  const values = itemList.map((item) => item.value);
> > 本身的依赖是 itemList，没啥问题，应该是没问题的。
> 
> 这个地方我改一下跑个单测确认一下，我觉得不能解决问题

你是对的，我重新更新一下内容
我被之前的 0 逻辑误解了

2022-08-12 08:47 UTC, HQ-Lin commented
更新下snapshot

2022-08-12 15:38 UTC, NWYLZW commented
> 更新下snapshot

我的问题应该不是因为 snapshot，我没有改动 example
我看了一下挂掉的原因
tab bar 的 style 在 describe 和 test 俩个级别下的测试结果不一样
我上一个 commit 都没有这个问题来着
可能是修改的内容导致的

2022-08-15 08:22 UTC, HQ-Lin approved these changes

2022-08-15 08:24 UTC, LeeJim approved these changes

2022-08-15 08:25 UTC, merged