feat(tabs): supports scrolling operations via wheel or touchpad
Tencent/tdesign-react pull request #2929
Opened 2024-05-28 13:18 UTC by oljc

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

详见：[498](https://github.com/Tencent/tdesign/issues/498)

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2024-05-29 01:27 UTC, HaixingOoO commented
> @HaixingOoO @NWYLZW 有空一起看看这个咯 如果react这边逻辑没问题我们就推API的录入和vue那边的跟进 🤔

ok，有空時候看看！

2024-06-03 04:07 UTC, NWYLZW requested changes

2024-06-03 04:07 UTC, NWYLZW commented on src/tabs/TabNav.tsx
> +    setTimeout(() => {
注意回收副作用

2024-06-03 04:07 UTC, NWYLZW commented on src/tabs/TabNav.tsx
> +    if (scrollBar) {
scrollBar 的处理逻辑有问题，加一下 early return，否则 dispose 的时候处理可能会出现 null 上的访问

2024-06-03 04:07 UTC, NWYLZW commented on src/tabs/TabNav.tsx
> +    getMaxScrollLeft();
使用 useCallback

2024-06-03 06:10 UTC, HaixingOoO commented on src/tabs/TabNav.tsx
> +    getMaxScrollLeft();
這個使用`useCallback`了，在上面`88`行

2024-06-03 06:13 UTC, NWYLZW commented on src/tabs/TabNav.tsx
> +    getMaxScrollLeft();
> 這個使用`useCallback`了，在上面`88`行

我的意思就是用了 usecallback 了，依赖写错了，应该直接直接写 useCallback 返回的 `getMaxScrollLeft`。

2024-06-03 07:33 UTC, oljc commented on src/tabs/TabNav.tsx
> +    getMaxScrollLeft();
这里` itemList` `children` 也作为依赖项，是想着选项增删操作的时候也执行 `getMaxScrollLeft`。

2024-06-03 08:05 UTC, NWYLZW approved these changes

2024-06-03 09:53 UTC, HaixingOoO approved these changes

2024-06-03 16:34 UTC, NWYLZW requested changes
common 冲突了，你可能需要处理一下这个问题

2024-06-04 03:10 UTC, NWYLZW approved these changes

2024-06-05 15:59 UTC, merged