feat(select): select scrollTop #639
Tencent/tdesign-react pull request #659
Opened 2022-04-20 09:43 UTC by smilebuz

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [ ] 文档改进
- [x] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [x] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

[#639 ](url)

### 💡 需求背景和解决方案

解决问题：列表选择体验优化，自动定位至选中的 option 区域
实现：展开时重新计算 select 的 scrollTop
单选效果
![image](https://user-images.githubusercontent.com/13402508/164200031-861fa6de-3098-4125-b70c-68d1115ab5c7.png)
多选效果
![image](https://user-images.githubusercontent.com/13402508/164200048-8b84ccd6-ad90-4458-ab10-288b82ee3def.png)

### 📝 更新日志

- feat(select): 列表选择体验优化，自动定位至选中的 option 区域

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-04-20 15:28 UTC, uyarn commented on src/select/base/Select.tsx
> +        const firstSelectedNode = document.querySelector(`.${classPrefix}-is-selected`) as HTMLDivElement;
这样执行document.querySelector，在SSR的场景下会有问题，需要调整一下实现，或者判断一下环境再执行比较好。

2022-04-21 07:14 UTC, HQ-Lin commented
`git config email` 更改一下,使用个人的不要用tencent

2022-04-21 08:12 UTC, HQ-Lin commented on src/select/base/Select.tsx
> +    const updateScrollTop = useMemo(
如果是函数的话是不是用 useCallback 更合适点

2022-04-21 18:58 UTC, uyarn requested changes

2022-04-21 18:58 UTC, uyarn commented on src/select/base/Select.tsx
> +        const firstSelectedNode = document.querySelector(`.${classPrefix}-is-selected`) as HTMLDivElement;
这样执行document.querySelector，在SSR的场景下会有问题，需要调整一下实现，或者判断一下环境再执行比较好。

2022-04-22 03:08 UTC, smilebuz commented on src/select/base/Select.tsx
> +    const updateScrollTop = useMemo(
同意，我改下

2022-04-22 05:48 UTC, HQ-Lin commented on src/select/base/Select.tsx
> +        const firstSelectedNode = document.querySelector(`.${classPrefix}-is-selected`) as HTMLDivElement;
这里用document搜索范围太大了，能否改成在具体的panel面板下去搜索dom子节点？也可以顺便解决document不存在的问题

2022-04-22 07:11 UTC, smilebuz commented on src/select/base/Select.tsx
> +        const firstSelectedNode = document.querySelector(`.${classPrefix}-is-selected`) as HTMLDivElement;
嗯，我改为在列表的 ref.current 下搜索

2022-04-24 02:25 UTC, HQ-Lin approved these changes

2022-04-24 02:26 UTC, HQ-Lin commented
https://preview-pr659-tdesign-react.surge.sh/react/demos/select/scroll-top
looks good

2022-04-24 02:58 UTC, uyarn approved these changes

2022-04-24 02:58 UTC, merged