fix(select): process multi-selected default selection disable logic #740
Tencent/tdesign-react pull request #765
Opened 2022-05-15 10:21 UTC by PBK-B

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [x] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue
https://github.com/Tencent/tdesign-react/issues/740

### 💡 需求背景和解决方案
Select 实现部分选项默认选中且对用户禁用，如下图
![168286782-63234012-6192-4f8a-a32a-8dd72dae9fb2](https://user-images.githubusercontent.com/39079814/168467849-590d85c8-8aa2-4119-a96a-11aa6586645a.png)

### 📝 更新日志

- [x] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-05-16 10:47 UTC, uyarn commented
@PBK-B 之前确实没有处理issue提到的这个场景；
你的改动引入了其他问题 upShowClearIcon的逻辑影响到了正常可选选项的关闭按钮
<img width="389" alt="image" src="https://user-images.githubusercontent.com/26377630/168576622-7be8a5e6-87bd-4558-b9e3-62617630effa.png">

2022-05-16 10:47 UTC, uyarn requested changes
@PBK-B 之前确实没有处理issue提到的这个场景；
你的改动引入了其他问题 upShowClearIcon的逻辑影响到了正常可选选项的关闭按钮
<img width="389" alt="image" src="https://user-images.githubusercontent.com/26377630/168576622-7be8a5e6-87bd-4558-b9e3-62617630effa.png">

2022-05-16 12:31 UTC, PBK-B commented
> @PBK-B 之前确实没有处理issue提到的这个场景； 你的改动引入了其他问题 upShowClearIcon的逻辑影响到了正常可选选项的关闭按钮 <img alt="image" width="389" src="https://user-images.githubusercontent.com/26377630/168576622-7be8a5e6-87bd-4558-b9e3-62617630effa.png">

@uyarn 我是在分析了 select-input 组件之后发现，在处理 TagInput 的时候拿到的 options 是没有配置项数据的原对象的，只是一个 label 数组，如果从 select 传递的话这边涉及的改动会很多层，从整个业务逻辑来看目前这个改动是能实现这个需求的最小改动。


从需求上说，如果 options 参数中不存在任何禁用选项的话，这个改动并不会影响之前的正常可选选项的关闭按钮，如下图
<img width="591" alt="截屏2022-05-16 下午7 55 29" src="https://user-images.githubusercontent.com/39079814/168587272-f6012462-1208-4b97-8ccc-79a0962db4ff.png">
<img width="461" alt="截屏2022-05-16 下午7 56 14" src="https://user-images.githubusercontent.com/39079814/168587386-e18a53e2-b2f4-4a05-912e-066bdf955668.png">

只有满足 options 参数中存在有选项被禁用后，才会设置 upShowClearIcon 禁用输入框中的关闭按钮。

2022-05-16 12:36 UTC, PBK-B commented
@uyarn 我刚刚又思考了一下，觉得再加一个条件会更合理。只有满足 value 默认选中的选项中包含 options 中配置被 disabled 禁用的选项才会默认设置 upShowClearIcon 禁用输入框中的关闭按钮。
这样既能实现需求又影响相对较小，我现在补充提交 commit ，你看如何。

2022-05-30 15:03 UTC, uyarn commented
fixed #815

2022-05-30 15:03 UTC, closed without merging